---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  PublicSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select a public subnet in your selected VPC.  The web server will run here.

  RepositoryUrl:
    Type: String
    Description:  URL of a Git repository that you wish to clone into this EnvironmentEC2
    Default: https://github.com/kennyk65/aws-teaching-demos

  InstanceType:
    Type: String 
    AllowedValues: 
    - t2.micro
    - t3.micro
    - t3.small
    - t3.medium
    - t3.xlarge
    Default: t3.micro
    Description: Select the backing EC2 instance type.


Resources:
  Cloud9: 
    Type: AWS::Cloud9::EnvironmentEC2 
    Properties: 
      Name: !Sub ${AWS::StackName} 
      ImageId: resolve:ssm:/aws/service/cloud9/amis/amazonlinux-2-x86_64
      InstanceType: !Ref InstanceType 
      AutomaticStopTimeMinutes: 60
      SubnetId: !Ref PublicSubnet 
      Repositories: 
        - PathComponent: /git
          RepositoryUrl: !Ref RepositoryUrl

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Please supply the following"
        Parameters: 
          - PublicSubnet
          - RepositoryUrl

Outputs:
  Cloud9Console:
    Description: Click here to go to the Cloud9 console
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/home?region=${AWS::Region}#