AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for an ECS Express Gateway (or Mode) Service with required IAM roles.

#  See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/express-service-overview.html
#  The idea with an express mode service is a bit like PaaS - it provides the task, service, load balancer, TLS, etc.
#  You provide the image.


Parameters:
  Image:
    Type: String
    Description: The container image to run in the ECS Express Gateway Service.
    Default: public.ecr.aws/nginx/nginx:latest

  Cluster:
    Type: String
    Description: Short name or full Amazon Resource Name (ARN) of the ECS cluster.
    Default: default

Resources:
  # 1. ECS Task Execution Role (ecsTaskExecutionRole in CLI)
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      # Prefix the role name with the stack name as requested
      RoleName: !Sub "${AWS::StackName}-ecsTaskExecutionRole"
      
      # The trust policy document from the CLI command
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
            
      # Attach the AWS managed policy using its ARN
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # 2. ECS Infrastructure Role for Express Services (ecsInfrastructureRoleForExpressServices in CLI)
  ECSInfrastructureRole:
    Type: AWS::IAM::Role
    Properties:
      # Prefix the role name with the stack name as requested
      RoleName: !Sub "${AWS::StackName}-ecsInfrastructureRoleForExpressServices"
      
      # The trust policy document from the CLI command
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ecs.amazonaws.com"
            Action: "sts:AssumeRole"
            
      # Attach the AWS managed policy using its ARN
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSInfrastructureRoleforExpressGatewayServices

  # 3. ECS Express Gateway Service (create-express-gateway-service in CLI)
  ECSExpressGatewayService:
    Type: AWS::ECS::ExpressGatewayService
    Properties:
      ServiceName: !Sub ${AWS::StackName}-nginx-express
      Cluster: !Ref Cluster
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      InfrastructureRoleArn: !GetAtt ECSInfrastructureRole.Arn
      PrimaryContainer:
        Image: !Ref Image

Outputs:
  PublicIngressPath:
    Description: Find the "Public Access Path" on this page to access the service
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/ecs/v2/clusters/${Cluster}/express-services/${AWS::StackName}-nginx-express
