AWSTemplateFormatVersion: 2010-09-09

# This CloudFormation template sets up a CloudWatch custom metric demo.

Parameters:

  Prefix:
    Description: Unique prefix of the environment
    Type: String
    Default: kk-cwdemo

  S3Bucket:
    Description: Bucket containing the existing WAR file.  Must be in same region as this stack.
    Type: String
    Default: kk-uploads-oregon

  S3Object:
    Description: Object key of the CloudWatch Demo WAR file in the S3 bucket
    Type: String
    Default: spring-cloud-aws-cloudwatch-demo-1.war

  EmailAddress:
    Description: Eamail address to send alerts to
    Type: String
    Default: kenkrueger65@gmail.com


Resources:

  # This Role is given to the ElasticBeanstalk environment:
  BeanstalkServiceRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub CloudWatchBeanstalkServiceRole-${AWS::StackName}  
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          Principal:
            Service: "elasticbeanstalk.amazonaws.com"
          Action: "sts:AssumeRole"

  # This Policy is attached to the BeanstalkServiceRole.
  BeanstalkServicePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub CloudWatchBeanstalkServicePolicy-${AWS::StackName}
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          # I'm not sure exactly what permissions are needed here.  Docs are nearly impossible.
          Action: 
            - elasticbeanstalk:*
            - elasticloadbalancing:Describe*
            - ec2:Describe*
            - ec2:Get*
            - ec2:Associate*
            - logs:*
            - s3:*
            - autoscaling:*   
          Resource: 
            - "*"
      Roles: 
        -  !Ref BeanstalkServiceRole

  # This Role is given to the EC2 instance(s) run by ElasticBeanstalk:
  BeanstalkAppRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: !Sub CloudWatchBeanstalkAppRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole

  # This Policy is attached to the BeanstalkAppRole, and eventually the EC2 instances.
  BeanstalkAppPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Sub CloudWatchBeanstalkAppPolicy-${AWS::StackName}
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          Effect: Allow
          # Permission requirements vary from app to app, but everyone needs cloudwatch logs.
          Action: 
            - logs:Create*
            - logs:GetLogEvents
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutRetentionPolicy
            - cloudwatch:Put*
          Resource: 
            - "*"
      Roles: 
        -  !Ref BeanstalkAppRole

  # Beanstalk starts here.
  MyBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub CloudWatchDemo-${AWS::StackName}

  # How to get the code:
  MyVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref MyBeanstalkApplication
      Description: v1
      SourceBundle:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Object

  # How to run the code:
  EBEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref MyBeanstalkApplication
      VersionLabel: !Ref MyVersion
      EnvironmentName: CloudWatchDemo
      CNAMEPrefix: !Ref Prefix
      # SolutionStackName: "64bit Amazon Linux 2018.03 v3.1.6 running Tomcat 8.5 Java 8" # Doesn't stream required log file
      SolutionStackName: "64bit Amazon Linux 2018.03 v2.7.4 running Java 8"
      OptionSettings: 
        - Namespace: aws:elasticbeanstalk:application
          OptionName: "Application Healthcheck URL"
          Value: /

        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref BeanstalkServiceRole        # What is the ElasticBeanstalk service allowed to do?
        
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref MyBeanstalkInstanceProfile  # What is the code on my EC2 instance allowed to do?

        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: SingleInstance                   # No load balancer please.

        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: SERVER_PORT
          Value: 5000                             # Spring Boot likes to listen on 8080, but EB expects 5000.  Easier to change Boot and EB.

        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: StreamLogs
          Value: true                             # Turn CloudWatch logs on.

        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: RetentionInDays
          Value: 3                                # Keep logs a few days.


  # Attaches the role to the instance:
  MyBeanstalkInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub BeanstalkInstanceProfile-${AWS::StackName}  
      Roles: [!Ref BeanstalkAppRole] 


  # # Un-comment this to make use a metrics filter to collect the metric;
  # # The metric filter assumes the name of the EB environment, and is specific to Tomcat application logs.
  # MetricFilter:
  #   Type: AWS::Logs::MetricFilter
  #   Properties: 
  #     # This log group is assumed to be created by the EB environment:
  #     LogGroupName: /aws/elasticbeanstalk/CloudWatchDemo/var/log/web-1.log
  #     # Line of output looks like:  "...com.example.MonitoringService  : Boredom Level: 68"
  #     FilterPattern: "[..., boredom=Boredom, level=\"Level:\", amount]"
  #     # Extract the actual boredom amount as our metric:
  #     MetricTransformations: 
  #       - MetricNamespace: Training
  #         MetricName: BoredomLevelFromLog
  #         MetricValue: $amount

  # # Uncomment this to raise an alarm on high boredom
  # # Fire alarm when Boredom becomes excessive:
  # HighBoredomAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmDescription: Fire alarm when boredom goes over 90%
  #     Namespace: Training
  #     MetricName: BoredomLevel
  #     Statistic: Average
  #     ComparisonOperator: GreaterThanThreshold
  #     Threshold: 90
  #     EvaluationPeriods: 1
  #     Period: 60
  #     AlarmActions:
  #       - !Ref SnsTopic

  # # Topic to send email alerts to, when boredom is excessive:
  # SnsTopic:
  #   Type: AWS::SNS::Topic
  #   Properties: 
  #     DisplayName: Boredom Alert! 
  #     TopicName: BoredomAlert
  #     Subscription:
  #       - Endpoint: !Ref EmailAddress
  #         Protocol: email


Outputs:
  ProductionURL:
    Value: !Sub http://${EBEnvironment.EndpointURL}