AWSTemplateFormatVersion: '2010-09-09'
#  This template illustrates three separate ways to connect two VPCs,
#  VPC Peering, Transit Gateway, and VPC (Interface) Endpoints.
#  It launches EC2 instances in the source and destination VPCs to
#  make the connectivity easier to demonstrate.  It also provides a 
#  quick link to the network reachability page in the management console 
#  to graphically show the network components.
#
#  To demonstrate VPC peering, create the stack with option 1.  Find the 
#  private IP address of the destination instance in the stack output.  Use
#  the session manager link to connect to the source instance.  Ping the
#  destination instance like this:   ping -c 6 <IP-ADDRESS>
#
#  To demonstrate Transit Gateway, create the stack with option 2.  Follow the
#  same demo ideas for peering.
#
#  To demonstrate VPC Endpoints / Private Link, create the stack with option 3.
#  The destination instance hosts a small web service (Python/Flask in a Docker container)
#  Which can be called via the VPC Endpoint's DNS name.  Copy it from stack
#  output and call the web service like this:  http://<DNSNAME>/api?value=2 .
#  
#  Optional: For any of these options, use the link in stack output to open
#  VPC / Network Manager / Reachability Analyzer.  Enter source as consumer 
#  instance, target as provider instance.


Parameters:

  VPCConnectionType:
    Type: String
    AllowedValues: 
    - 1. Use VPC Peering
    - 2. Use Transit Gateway
    - 3. Use Endpoint
    Default: 1. Use VPC Peering
    Description: How would you like to connect the two VPCs?

  DockerImage:
    Type: String
    Default: public.ecr.aws/kkrueger/flask-api:1
    Description: Image to use for a container.  Can be from DockerHub or include registry URL for a different source (repository-url/image:tag). 

  AmazonLinuxAMI:
    Type:  AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: You probably won't need to change this value.  This is looking up the latest Amazon Linux 2 AMI using the Parameter Store...

Conditions:
  UsePeeringCondition:          !Equals [ !Ref VPCConnectionType, "1. Use VPC Peering" ]
  UseTransitGatewayCondition:   !Equals [ !Ref VPCConnectionType, "2. Use Transit Gateway" ]
  UseEndpointCondition:         !Equals [ !Ref VPCConnectionType, "3. Use Endpoint" ]

Resources:

  #  Provider network:
  ProviderVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Provider VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-ProviderIGW
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ProviderVPC
      InternetGatewayId: !Ref InternetGateway

  ProviderSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProviderVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list  
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: True
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Provider Subnet

  ProviderRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProviderVPC
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Provider Route table

  ProviderRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref ProviderRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  ProviderRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ProviderRouteTable
      SubnetId: !Ref ProviderSubnet

  ProviderSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-ProviderSecurityGroup
      GroupDescription: ProviderSecurityGroup
      VpcId: !Ref ProviderVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-ProviderSecurityGroup

  ProviderInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"  # Obtain the AMI from the SSM Parameter
      InstanceType: t2.micro
      SubnetId: !Ref ProviderSubnet
      SecurityGroupIds:
      - !Ref ProviderSecurityGroup
      IamInstanceProfile: !Ref SSMInstanceProfile     # Allows EC2 Instance to talk with SSM, just in case we need to debug something
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Provider Instance
      UserData:                           # Starts a simple web app on port 80
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker
          service docker start
          docker pull ${DockerImage}
          docker run -d -p80:5000 ${DockerImage}   


  # This is the Consumer network
  ConsumerVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Consumer VPC 

  ConsumerInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-ConsumerIGW
  ConsumerInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ConsumerVPC
      InternetGatewayId: !Ref ConsumerInternetGateway

  ConsumerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ConsumerVPC
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list  
      CidrBlock: 172.16.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Consumer Subnet

  ConsumerRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ConsumerVPC
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Consumer Route Table

  ConsumerRoute:
    Type: AWS::EC2::Route
    DependsOn: ConsumerInternetGatewayAttachment
    Properties:
      RouteTableId: !Ref ConsumerRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref ConsumerInternetGateway

  ConsumerRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref ConsumerRouteTable
      SubnetId: !Ref ConsumerSubnet

  ConsumerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${AWS::StackName}-ConsumerSecurityGroup
      GroupDescription: ConsumerSecurityGroup
      VpcId: !Ref ConsumerVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 172.16.0.0/16
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-ConsumerSecurityGroup

  ConsumerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"  # Obtain the AMI from the SSM Parameter
      InstanceType: t2.micro
      SubnetId: !Ref ConsumerSubnet
      IamInstanceProfile: !Ref SSMInstanceProfile     # Allows EC2 Instance to talk with SSM
      SecurityGroupIds:
      - !Ref ConsumerSecurityGroup
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName} Consumer Instance

  # Attach AmazonEC2RoleforSSM's permissions to each EC2 Instance in the ASG.
  SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles: [ !Ref SSMRole]

  # Allow EC2 instance to make calls to SSM, including session manager.
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: ec2.amazonaws.com
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  # PEERING STARTS HERE!!
  PeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Condition:  UsePeeringCondition
    Properties: 
      PeerVpcId: !Ref ProviderVPC
      VpcId: !Ref ConsumerVPC

  ProviderPeerRoute:
    Type: AWS::EC2::Route
    Condition:  UsePeeringCondition
    Properties:
      RouteTableId: !Ref ProviderRouteTable
      DestinationCidrBlock: 172.16.0.0/16
      VpcPeeringConnectionId: !Ref PeeringConnection

  ConsumerPeerRoute:
    Type: AWS::EC2::Route
    Condition:  UsePeeringCondition
    Properties:
      RouteTableId: !Ref ConsumerRouteTable
      DestinationCidrBlock: 10.0.0.0/16
      VpcPeeringConnectionId: !Ref PeeringConnection

  # TRANSIT GATEWAY STARTS HERE
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Condition: UseTransitGatewayCondition
    Properties: 
      AutoAcceptSharedAttachments: enable   # Hoping this makes attaching VPCs easier

  ConsumerTransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Condition: UseTransitGatewayCondition
    Properties: 
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref ConsumerVPC
      SubnetIds: 
      - !Ref ConsumerSubnet

  ProviderTransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Condition: UseTransitGatewayCondition
    Properties: 
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref ProviderVPC
      SubnetIds: 
      - !Ref ProviderSubnet

  ConsumerTransitGatewayRoute: 
    Type: AWS::EC2::Route
    Condition: UseTransitGatewayCondition
    DependsOn: ConsumerTransitGatewayAttachment
    Properties: 
      RouteTableId: !Ref ConsumerRouteTable
      DestinationCidrBlock: 10.0.0.0/16
      TransitGatewayId: !Ref TransitGateway

  ProviderTransitGatewayRoute: 
    Type: AWS::EC2::Route
    Condition: UseTransitGatewayCondition
    DependsOn: ProviderTransitGatewayAttachment
    Properties: 
      RouteTableId: !Ref ProviderRouteTable
      DestinationCidrBlock: 172.16.0.0/16
      TransitGatewayId: !Ref TransitGateway

  # PRIVATE LINK STARTS HERE!!
  # This is the Private Link VPC Endpoint Service.  This endpoint will be avalilable outside the Provider VPC to those who need to consume it.
  ConsumerEndPointService:
    Type: AWS::EC2::VPCEndpointService
    Condition:  UseEndpointCondition
    Properties:
      NetworkLoadBalancerArns:
      - !Ref NetworkLoadBalancer
      AcceptanceRequired: false

  # This is the Consumer endpoint.  It resides in the source VPC/Subnets and sends traffic to the destination VPC Endpoint.
  ConsumerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition:  UseEndpointCondition
    Properties:
      VpcId: !Ref ConsumerVPC
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.vpce.${AWS::Region}.${ConsumerEndPointService}
      SubnetIds:
      - !Ref ConsumerSubnet
      SecurityGroupIds:
      - !Ref ConsumerSecurityGroup

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Condition:  UseEndpointCondition
    Properties:
      Name: !Sub ${AWS::StackName}-NLB
      Scheme: internal
      Subnets:
      - !Ref ProviderSubnet
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-NetworkLoadBalancer
      Type: network

  ProviderTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Condition:  UseEndpointCondition
    Properties:
      Name: !Sub ${AWS::StackName}-TG
      Port: 80
      Protocol: TCP
      VpcId: !Ref ProviderVPC
      TargetType: instance
      Targets:
      - Id: !Ref ProviderInstance
        Port: 80

  ProviderListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition:  UseEndpointCondition
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref ProviderTargetGroup
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 80
      Protocol: TCP


Outputs:

  ConsumerSessionManagerLink:
    Description: Access the service SOURCE using web browser.  
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/systems-manager/session-manager/${ConsumerInstance}?region=${AWS::Region}#  

  ProviderPrivateIpAddress:
    Description:  Private IP address of the destination EC2 instance.  Should be pingable from source instance when using Peering or Transit Gateway.
    Value: !GetAtt  ProviderInstance.PrivateIp

  ReachabilityAnalyzerLink:
    Description:  Convenient link to the Network Manager Reachability Analyzer.  Enter 'Consumer' instance as source and 'Provider' instance as target
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/networkinsights/home?region=${AWS::Region}#CreateNetworkPath

  DnsName:
    Description: DNS Name of the VPC Endpoint.  
    Condition:  UseEndpointCondition
    Value: !Select [1, !Split [ ':', !Select [ 0, !GetAtt ConsumerEndpoint.DnsEntries ]]]
