AWSTemplateFormatVersion: '2010-09-09'

# Accesses some parameters that were setup using template 1.

Parameters:

  ParameterA:
    Type:  AWS::SSM::Parameter::Value<String>
    Default: /STACK/key/a
    Description: Parameter A

  ParameterB:
    Type:  AWS::SSM::Parameter::Value<String>
    Default: /STACK/key/b
    Description: Parameter B

Resources:

  # This is only here because you cannot have a CloudFormation stack with 0 resources:
  UseLess:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub /${AWS::StackName}/delete/me
      Type: String    
      Value: delete this
      Description: Cant have a stack with no resources.

Outputs:
  ParameterAValue:
    Description: The value of parameter A.
    Value: !Ref ParameterA

  ParameterBValue:
    Description: The value of parameter B.
    Value: !Ref ParameterB

