AWSTemplateFormatVersion: 2010-09-09

# This CloudFormation template publishes some of my favorite demos into AWS Service Catalog.
# Once there it is easier to launch the stacks through Service Catalog then to hunt for the
# templates in my file system

Parameters:
  PrincipalARN:
    Description:  The IAM user, group, or role that will be given permission to provision the products in the resulting Portfolio.  Replace the ARN you see here with one appropriate to your account.  I suggest a user or group to make demonstration easy.
    Type:  String
    Default:  arn:aws:iam::011673140073:group/everybody


Resources:

  # A Portfolio is a collection of products that belong together:
  AwsDevPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: Hilltop Technology
      Description: Demo stacks suitable for the Developing on AWS course
      DisplayName: Classroom Demos
      AcceptLanguage: en

  ClassroomDemoPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: Hilltop Technology
      Description: A set of demo stacks suitable for various classroom demos
      DisplayName: Classroom Demos
      AcceptLanguage: en

  TechEssentialsPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      ProviderName: Hilltop Technology
      Description: Demos for use in the AWS Tech Essentials class
      DisplayName: AWS Technical Essentials Demos
      AcceptLanguage: en



  # Who is allowed to create products in this portfolio?
  AwsDevPermission:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref AwsDevPortfolio
      PrincipalARN: !Ref PrincipalARN
      PrincipalType: IAM                  # Lordy, there's only one possible value, and it is required...

  PortfolioPermission:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      PrincipalARN: !Ref PrincipalARN
      PrincipalType: IAM                  # Lordy, there's only one possible value, and it is required...

  TechEssentialsPermission:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref TechEssentialsPortfolio
      PrincipalARN: !Ref PrincipalARN
      PrincipalType: IAM                  # Lordy, there's only one possible value, and it is required...


  # XRay demo:
  XRay:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      Description: A simple XRay Demo.  An AWS-provided Elastic Beanstalk app serves up transactions to back end services
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: XRayDemo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/xray-demo-nodejs.template.yml
          Name: v1

  # StepFunctions Recognition:
  StepFunctionsRecognition:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      Description: StepFunctions demo featuring Amazon Recognition.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: StepFunctionsRecognition
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/stepfunction-recognition.template.yml
          Name: v1

  # AWS Dev Lab4 - Lambda:
  DevLab4:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      Description: Clone of Lab 4 from the Developing on AWS v4 course.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: AWSDevLab4
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/dev4-lab4.template.yml
          Name: v1

  # AWS Dev Lab5 - API Gateway:
  DevLab5:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      Description: Clone of Lab 5 from the Developing on AWS v4 course.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: AWSDevLab5
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/dev4-lab5.template.yml
          Name: v1

  # AWS Dev Lab6 - PollyNotes:
  DevLab6:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      Description: Clone of Lab 6 from the Developing on AWS v4 course.  This is the Capstone Pollynotes lab.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: AWSDevLab6
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/dev4-lab6.template.yml
          Name: v1

  # Associate products with Portfolio.  (why can't this just be a property of the Product?)
  DevLab6Assoc:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref AwsDevPermission
      ProductId: !Ref DevLab6
  DevLab5Assoc:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref AwsDevPermission
      ProductId: !Ref DevLab5
  DevLab4Assoc:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref AwsDevPermission
      ProductId: !Ref DevLab4
  StepFunctionsRecognitionAssoc:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref AwsDevPermission
      ProductId: !Ref StepFunctionsRecognition
  XRayAssoc:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref AwsDevPermission
      ProductId: !Ref XRay



  # This Product builds a VPC with Subnets under your direction:
  NetworkInABox:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See https://www.infoq.com/articles/aws-vpc-cloudformation for background on this template article.
      Description: A VPC with Subnets on-demand.  Choice between public and private, number of subnets, etc.  See https://www.infoq.com/articles/aws-vpc-cloudformation for background article.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: NetworkInABox
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/base-network.template.yml
          Name: v1

  # Associate product with Portfolio.  (why can't this just be a property of the Product?)
  PortfolioNetworkInABox:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref NetworkInABox

  # This Demo builds an EC2 instance running a Docker image you specify:
  DockerOnEc2Demo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/ec2-run-docker.template.yml
      Description: This launches an EC2 instance and runs a Docker image on it.  You can take a look at the instance's user data to see how it is done.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: DockerOnEc2Demo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/ec2-run-docker.template.yml
          Name: v1

  PortfolioDockerOnEc2Demo:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref DockerOnEc2Demo

  # This Demo builds a simple Step Functions example 
  StepFunctionsDemo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/stepfunction-beatles.template.yml
      Description: This product produces a simple Simple Step-Function demo.  The step function calls 4 separate lambda functions in sequence to piece together the words to the Beatles "A Day In the Life" song - featuring Ringo.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: StepFunctionsDemo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/stepfunction-beatles.template.yml
          Name: v1

  PortfolioStepFunctionsDemo:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref StepFunctionsDemo

  # Elastic Beanstalk Rolling Deployment Demo
  EBRollingDemo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/elasticbeanstalk-rolling-demo.template.yml
      Description: This product produces an Elastic Beanstalk application / environment with 4 instances.  Two versions of the app are available, v1 and v2.  When deploying v2 you can watch the rolling behavior.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: EBRollingDemo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/elasticbeanstalk-rolling-demo.template.yml
          Name: v1

  PortfolioEBRollingDemoDemo:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref EBRollingDemo

  # Elastic Beanstalk BlueGreen Deployment Demo
  EBBlueGreenDemo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/elasticbeanstalk-bluegreen-demo.template.yml
      Description: This product produces an Elastic Beanstalk application with two environments, a 'blue' mapped to a production url, and a 'green' mapped to a staging url.  Environment swap switches the two.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: EBBlueGreenDemo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/elasticbeanstalk-bluegreen-demo.template.yml
          Name: v1

  PortfolioEBBlueGreenDemo:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref EBBlueGreenDemo

  # Systems Manager Demo
  SystemsManagerDemo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/systems-manager-demo.template.yml
      Description: This product creates 4 EC2 instances running the SSM agent.  Use these as targets for session manager, EC2 run command, whatever.
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: SystemsManagerDemo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/systems-manager-demo.template.yml
          Name: v1

  PortfolioSystemsManagerDemo:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref SystemsManagerDemo

  # SAM Demo
  SAMDemo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/sam-demo.template.yml
      Description: This product creates an API Gateway backed by an imaginitive "Hello World" Lambda function.  
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: SAMDemo
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/sam-demo.template.yml
          Name: v1

  PortfolioSAMDemo:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ClassroomDemoPortfolio
      ProductId: !Ref SAMDemo

  # Tech Essentials Lab 1
  TessLab1:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/AWS-Tess-Lab1.yml
      Description: This product re-creates Lab 1 from the AWS Tech Essentials class in your own account.  
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: TechEssentialsLab1
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/AWS-Tess-Lab1.yml
          Name: v1

  PortfolioTessLab1:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref TechEssentialsPortfolio
      ProductId: !Ref TessLab1

  # Tech Essentials Lab 2
  TessLab2:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/AWS-Tess-Lab2.yml
      Description: This product re-creates Lab 2 from the AWS Tech Essentials class in your own account.  
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: TechEssentialsLab2
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/AWS-Tess-Lab2.yml
          Name: v1

  PortfolioTessLab2:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref TechEssentialsPortfolio
      ProductId: !Ref TessLab2

  # Tech Essentials Lab 3
  TessLab3:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Owner: Ken Krueger
      SupportDescription: See the source code for this CloudFormation template at https://github.com/kennyk65/aws-teaching-demos/blob/master/cloud-formation-demos/AWS-Tess-Lab3.yml
      Description: This product re-creates Lab 3 from the AWS Tech Essentials class in your own account.  
      Distributor: Hilltop Technology
      SupportEmail: kenkrueger65@gmail.com
      AcceptLanguage: en
      Name: TechEssentialsLab3
      ProvisioningArtifactParameters: 
        - Description: First Version
          Info: 
            LoadTemplateFromURL: https://raw.githubusercontent.com/kennyk65/aws-teaching-demos/master/cloud-formation-demos/AWS-Tess-Lab3.yml
          Name: v1

  PortfolioTessLab3:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref TechEssentialsPortfolio
      ProductId: !Ref TessLab3


Outputs:
  ServiceCatalogLink:
    Description: Click here to see the service catalog.
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/servicecatalog/home?isSceuc=true&region=${AWS::Region}#/products