default_agent: my_agent
agents:
  my_agent:
    name: my_agent
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::011673140073:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-e72c1a7c7a
      execution_role_auto_create: false
      account: '011673140073'
      region: us-west-2
      ecr_repository: 011673140073.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-my_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: my_agent-dxDxlD7I4i
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:011673140073:runtime/my_agent-dxDxlD7I4i
      agent_session_id: d4e8f54a-c426-4643-8cf5-8733136ac6e8
    codebuild:
      project_name: bedrock-agentcore-my_agent-builder
      execution_role: arn:aws:iam::011673140073:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-e72c1a7c7a
      source_bucket: bedrock-agentcore-codebuild-sources-011673140073-us-west-2
    authorizer_configuration: null
    oauth_configuration:
      workload_name: workload-ef6294b3
