default_agent: agentcore_demo_v2
agents:
  agentcore_demo:
    name: agentcore_demo
    entrypoint: my_agent.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::011673140073:role/BedrockAgentCoreExec-agentcore-demo
      execution_role_auto_create: true
      account: '011673140073'
      region: us-west-2
      ecr_repository: 011673140073.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-agentcore-demo
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_demo-o79XREG8Yw
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:011673140073:runtime/agentcore_demo-o79XREG8Yw
      agent_session_id: 64b907f4-8cc4-426f-9999-a224ffab2d12
    codebuild:
      project_name: bedrock-agentcore-agentcore_demo-builder
      execution_role: arn:aws:iam::011673140073:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-0e2c6e4184
      source_bucket: bedrock-agentcore-codebuild-sources-011673140073-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
  agentcore_demo_v2:
    name: agentcore_demo_v2
    entrypoint: my_agent_v2.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::011673140073:role/BedrockAgentCoreExec-agentcore-demo-2
      execution_role_auto_create: true
      account: '011673140073'
      region: us-west-2
      ecr_repository: 011673140073.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-agentcore-demo-2
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_demo_v2-yg65zE84CT
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:011673140073:runtime/agentcore_demo_v2-yg65zE84CT
      agent_session_id: a68ade06-438d-4f15-a534-6d5cb5fded1b
    codebuild:
      project_name: bedrock-agentcore-agentcore_demo_v2-builder
      execution_role: arn:aws:iam::011673140073:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-c2b0d5652d
      source_bucket: bedrock-agentcore-codebuild-sources-011673140073-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
